/*
 * Author: Manideep
 * CreatedDate: 11/14/2017
 * Description: This is a Test class for the classes below
                * AutoCreateOppFutureQuarterSchEntry_Batch
                * AutoCreateOpptyforFutureQuarterSchEntrys 
	2017.11.29 - PJENA - Code Cleanup - ready to be deleted
*/

@isTest
private class AutoIdentifyErrorsOppFutrQuarterSE_Test {
 
	private static testMethod void SEQuarterGreaterthenOppCloseDateQuarterforOpenOpps() {
		AutoIdentifyErrorOppFutrQuarterSE_Batch oAutoIdentifyErrorOppFutrQuarterSE_Batch = new AutoIdentifyErrorOppFutrQuarterSE_Batch();
		AutoIdentifyErrorsOppFutureQuarterSE oAutoIdentifyErrorsOppFutureQuarterSE = new AutoIdentifyErrorsOppFutureQuarterSE();
	}

}