/*
 * Author: Manideep
 * CreatedDate: 11/14/2017
 * Description: This is a Test class for the classes below
                * AutoCreateOppFutureQuarterSchEntry_Batch
                * AutoCreateOpptyforFutureQuarterSchEntrys   
	
	2017.11.29 - PJENA - Code Cleanup - ready to be deleted
*/

@isTest
private class AutoCreateOpptyforFutureQuarterSE_Test {
 
 	private static testMethod void SEQuarterGreaterthenOppCloseDateQuarterforOpenOpps() {
   		AutoCreateOppFutureQuarterSchEntry_Batch oAutoCreateOppFutureQuarterSchEntry_Batch = new AutoCreateOppFutureQuarterSchEntry_Batch();
   		AutoCreateOpptyforFutureQuarterSchEntrys oAutoCreateOpptyforFutureQuarterSchEntrys = new AutoCreateOpptyforFutureQuarterSchEntrys();
	}

}