/*
 * Created By: Manideep
 * CreatedDate: 11/14/2017
 * Description: This class is invoked by Batch  class 'AutoIdentifyMisMatchOLIandSchEntry_Batch' to identify Opportunities that has 
                mismatch in Revenues between OpportunityLineItems and Schedule Entries. 
	
	2017.11.29 - PJENA - Code Cleanup - ready to be deleted
	
*/
public class AutoIdentifyMisMatchOLIandSchEntrys {
   public AutoIdentifyMisMatchOLIandSchEntrys(){}
}