/*
	Controller class for CRM_DR_SubmitClaimForApproval page
	
	Change List:
	2016.12.14 - Opp Registration TAM - interim change
	
	2017.03.13 - Opp Reg 2.0 (Phase I) - TAM Automation, Direct Opp Reg record creation, Regional Roll-out
	
	2017.06.05 - Bug Fix - Opp Reg : Alt Partner Owner - use DR_Partner_Owner__c.CreatedBy when CreatedBy.Contact (User) is inactive
	
	2017.08.23 - Restrict Partners Closing Out Opportunity Regs 
		Blankout code so it can be cleaned up later
	
	2017.11.29 - PJENA - Deal Registration - Code Cleanup - ready to be deleted	
*/

public class CRM_DR_SubmitClaimForApproval_cls {
	//constructor
	public CRM_DR_SubmitClaimForApproval_cls(){}
}