/*
	Controller class for CRM_DR_MakeADeal vf page
	
	Change list:
	2016.05.28 - code changes required for openinig up Opportunity Reg for all Enterprise
	2016.12.14 - Opp Registration TAM - interim change 
	
	2017.08.23 - Restrict Partners Closing Out Opportunity Regs 
		Blankout code so it can be cleaned up later
	2017.11.29 - PJENA - Deal Registration - Code Cleanup
*/
public class CRM_DR_MakeADeal_cls {
	
	//constructor
	public CRM_DR_MakeADeal_cls(){}
	
}