/* @Manideep: 5/8/2019 - This code is commented out as part of Opportunity RecordType clean up. This is an old code
                           and is not being used. 
*/ 
public class ItemsToApproveOverrideVF_Controller {
   
   // Dummy method for code coverage
   // This method is coverred by the class 'UnitTests_DummyCodeCoverage_DEL_Classes.cls'
   public static void fakeMethod(){
     Integer i = 0;
     i++;
   }
   
   /* 
    * @Manideep - Opportunity RecordType Cleanup  
    public string getItemsToApprovePageMarkup() {
        string pageContent = (new PageReference('/04i?lsi=1&rowsperpage=1000').getContent().tostring());
        return pageContent;
    }
   */    
}