/*
 * Author: Manideep
 * Description: This is a wrapper object for Lead Assignment Service.
 
 * 03/31/2020 : @Manideep - SDS-2104: Remove APAC LSID and NPN Nurture Routing Rules.
 * 06/02/2020 : @Manideep - SDS-2276: Automotive Lead Routing basing on Product Type 'Automotive' and Company Type field.

 *** 02/04/2021: @Manideep - SDS-2795: This Class is ready to Delete, so commenting out as of now because unable to delete due to failures in other test classes in the Org. ***
 
*/
global class LeadAssignmentTemplate { 
  /*
  global Id LeadId;
  //global String LeadLSID;
  //global String PartnerLeadOwner;
  global String AccountId;
  global String Country;
  global String State;
  global String ProductType;
  global String EnterpriseSegment;
  global String CompanyType;
  global String Industry;
  global Id OwnerId; 
  global String Region;
  global String LeadOrigin;
  global Id RecordTypeId;
  */
  
  // This is dummy method for the code coverage purpose
  public void ccMethod() {}
  
  
}