/*
 * 1/22/2018: @Manideep: commenting out this class as part of Oppty Record Type cleanup.
 * 6/12/2018: @Manideep: Added fakeMethod() for code coverage as this class is commented out.
*/
public class Opportunity_ReEngineering_Constants {
	
	// Dummy method for code coverage
    // This method is coverred by the class 'UnitTests_DummyCodeCoverage_DEL_Classes.cls'
    public static void fakeMethod(){
      Integer i = 0;
      i++;
    }
	
	/*
	public static final string RT_NOTEBOOK_OPPORTUNITY = 'Notebook Opportunity';
	
	//public static final string PROF_SYSADMIN = 'System Administrator';
	
	// @Manideep - Disable Schedule Entry capability for Future Quarters and do not copy over Schedule Entries while Cloning Opportunity
	public static final string RT_Disable_ScheduleEntry_For_Clone = 'Tesla Sales Opportunity;Tesla Partner Deal;Quadro Sales Opportunity;Quadro Partner Deal;GRID Sales Opportunity;GRID Partner Deal';
	*/
}