/******************************************************************************************
Name                : ScheduleRecentlyAddedFileJob 
Author              : Appirio Offshore(Aslam Bari)
Date                : June 04, 2010
Description         : This class calls the 'runDocUpdate()' method
                      of UpdateRecentlyAddedFilesDoc class on schedule basis
                      
2017.11.29 - PJENA - Code Cleanup - ready to be deleted

******************************************************************************************/
public class ScheduleRecentlyAddedFileJob{
	public ScheduleRecentlyAddedFileJob(){}
	  
	@isTest private static void test_TestHelp(){
    	ScheduleRecentlyAddedFileJob obj1 = new ScheduleRecentlyAddedFileJob();
	} 
	
}