public with sharing class ServiceCloudConstants { 
	public ServiceCloudConstants() {
		
	}
    /*public static final Set<string> CUSTOMER_PROFILES 	= new Set<string>{'ESP Community User', 'NVES Community User Non-Admin'};
    public static final Set<string> AGENT_PROFILES 		= new Set<string>{'Service Cloud Generic User'};
    public static final Set<string> INTERNAL_USERTYPES 	= new Set<string>{'Standard'};
    public static final boolean ACTIVE_ENTITLEMENTS_ONLY= FALSE;
    public static final string SUPPORT_PORTAL = 'Support Portal';
    public static final string LICENSING_PORTAL = 'Licensing Portal';
    public static final map<String, String> OBJECT_TO_ACTIVITY_TYPE_MAP 
    													= new map<String, String>{
															'Attachment'	=> 'Attachment', 
															'ContentDocumentLink'=> 'Attachment', 
															'EmailMessage' 	=> 'Email Message', 
															'CaseComment' 	=> 'Case Comment'
														}; 
	*/
	//public static final map<String, String> PRODUCTLINE_TO_PORTALMAP 
    //													= new map<String, String>{
	//														'DGX'	=> 'Attachment', 
	//														'DRIVE Constellation'=> 'Attachment', 
	//														'EmailMessage' 	=> 'Email Message', 
	//														'CaseComment' 	=> 'Case Comment'
	//													};
}