/*
 * Author: Manideep
 * CreatedDate: 2/17/2017
 * Description: This is a Service Class. The class is utilized by the 'TAM_Utility_Class' as a wrapper.                
*/

global class TAMSObjectRecTemplate { 
  global String allFields; 
  global String Id;
  global String Region;
  global String Country;
  global String State;
  global String City;
  global String Industry;
  global String TAMId;
  global String errMsg; 
  
  // This is dummy method for the code coverage purpose
  public void ccMethod() {}
  
}