/**
Name            :       Test_Help
Created By      :       Appirio Offshore(Rishi Khirbat)
Created On      :       November 23, 2010
Description     :       
Related PR      :       PR-07226
Modified        :
*/
//2017.11.29 - PJENA - Code Cleanup - ready to be deleted

public class TestHelp {
	public TestHelp(){}
	
	@isTest
    private static void test_TestHelp(){
		TestHelp obj1 = new TestHelp();
    } 
}