/******************************************************************************************
Name                : TestBudgetTrigger
Author              : Appirio Offshore(Vipin P. Gupta)
Date                : Dec 22, 2010
Description         : Test code coverage for BudgetTrigger trigger
******************************************************************************************/
//2017.11.29 - PJENA - Code Cleanup - ready to be deleted

@isTest
private  class TestBudgetTrigger {
	static testMethod void testBudgetTrigger () {
		//do nothing
	}

}