/******************************************************************************************
Name                : TestUpdateRecentlyAddedFilesDoc
Author              : Appirio Offshore(Aslam Bari)
Date                : June 05, 2010
Description         : Test code coverage for UpdateRecentlyAddedFilesDoc class

2017.11.29 - PJENA - Code Cleanup - ready to be deleted

******************************************************************************************/
@isTest
public class TestUpdateRecentlyAddedFilesDoc{
    @isTest private static void testController(){}
}