/******************************************************************************************
Name                : TestSearchMarketingToolCategory
Author              : Appirio Offshore(Aslam Bari)
Date                : June 07, 2010
Description         : Test code coverage for SearchMarketingToolCategory class

2017.11.29 - PJENA - Code Cleanup - ready to be deleted

******************************************************************************************/
@isTest
public class TestSearchMarketingToolCategory{
    @isTest
    private static void testController(){}
}