/*
	2019.03.11 - PJENA - SDS-774 - Remove Partner Opportunity Record Types
		New Test class for Opportunity_ReEngineering_Constants which was not present earlier
		- removed the reference to Tesla Partner Deal, GRID Partner Deal and Quadro Partner Deal
 */
@isTest
private class Test_Opportunity_ReEngineering_Constants {

    static testMethod void myUnitTest() {
        Opportunity_ReEngineering_Constants clsORC = new Opportunity_ReEngineering_Constants();
    }
}