/*
	Test class for controller class CRM_DR_SubmitDealForApproval_cls
	2017.03.13 - Opp Reg 2.0 (Phase I) - TAM Automation, Direct Opp Reg record creation, Regional Roll-out
	
	2017.11.29 - PJENA - Deal Registration - Code Cleanup - ready to be deleted
	
 */
@isTest(SeeAllData=false)
private class Test_CRM_DR_SubmitDealForApproval_cls {
    static testMethod void testValidateAndSubmit() {
    	CRM_DR_SubmitDealForApproval_cls oCRM_DR_SubmitDealForApproval_cls = new CRM_DR_SubmitDealForApproval_cls();
    }
}