/******************************************************************************************
Name                : TestUpdateSearchMarketingToolDoc
Author              : Appirio Offshore(Aslam Bari)
Date                : June 05, 2010
Description         : Test code coverage for UpdateSearchMarketingToolDoc class
******************************************************************************************/
@isTest
public class TestUpdateSearchMarketingToolDoc{
    @isTest private static void testController(){}
}