/******************************************************************************************
Name                : TestImageFieldPopulator
Author              : Appirio Offshore(Aslam Bari)
Date                : June 05, 2010
Description         : Test code coverage for ImageFieldPopulator class

2017.11.29 - PJENA - Code Cleanup - ready to be deleted

******************************************************************************************/
public class TestImageFieldPopulator{
	@isTest private static void testController(){}
}