/*
	Test class for controller class CRM_DR_SubmitClaimForApproval_cls
	2016.12.14 - Opp Registration TAM - interim change
	2017.03.13 - Opp Reg 2.0 (Phase I) - TAM Automation, Direct Opp Reg record creation, Regional Roll-out
	
	2017.08.23 - Restrict Partners Closing Out Opportunity Regs 
		Blankout code so it can be cleaned up later
	
	2017.11.29 - PJENA - Deal Registration - Code Cleanup - ready to be deleted
*/

@isTest(SeeAllData=false)
private class Test_CRM_DR_SubmitClaimForApproval_cls {
	static testMethod void myUnitTest() {
       CRM_DR_SubmitClaimForApproval_cls oCRM_DR_SubmitClaimForApproval_cls = new CRM_DR_SubmitClaimForApproval_cls();
    }
}