/*
	Test class for controller class CRM_DR_MakeADeal_cls
	
	2017.08.23 - Restrict Partners Closing Out Opportunity Regs - Code clean up
	2017.11.29 - PJENA - Deal Registration - Code Cleanup
*/
 
@isTest(SeeAllData=false)
private class Test_CRM_DR_MakeADeal_cls {
    static testMethod void testMakeADeal_onclick() {
        CRM_DR_MakeADeal_cls oCRM_DR_MakeADeal_cls = new CRM_DR_MakeADeal_cls();
    }
}