/*
** Class: UnitTests_DummyCodeCoverage_DEL_Classes
** Description: Unit tests for the all the below existing classes

* @Manideep: 5/12/2019 - This is a new Class to cover code coverage for all below existing ready to delete Classes,
    - OpportunityReport_Controller.cls
    - ItemsToApproveOverrideVF_Controller.cls
    - EditOpportunityProduct_Extension.cls
    - EditOpportunityRecordType_Extension.cls
    - EditScheduleEntry_Extension.cls
    - SelectOppRecordType_Extension.cls
    - CloneOpportunityRecordType_Extension.cls
    - TegraTablet_OppAndProducts_Controller.cls
    - TegraAuto_OppAndProducts_Controller.cls
    - clsEditOpportunityProduct_ExtensionV2.cls
    - OpportunityAndProducts_Controller.cls
    
* @Manideep: 6/12/2019 - Add new classes with the dummy method for code coverage,
    - CreateScheduleEntries.cls
    - Opportunity_ReEngineering_Constants.cls
 
*/  
@isTest
private class UnitTests_DummyCodeCoverage_DEL_Classes{

  // Dummy test method for code coverage of dummy method in the controller class
  static testMethod void fakeTestMethod(){
     OpportunityReport_Controller.fakeMethod();
     ItemsToApproveOverrideVF_Controller.fakeMethod();
     EditOpportunityProduct_Extension.fakeMethod();
     EditOpportunityRecordType_Extension.fakeMethod();
     EditScheduleEntry_Extension.fakeMethod();
     SelectOppRecordType_Extension.fakeMethod();
     CloneOpportunityRecordType_Extension.fakeMethod();
     TegraTablet_OppAndProducts_Controller.fakeMethod();
     TegraAuto_OppAndProducts_Controller.fakeMethod();
     clsEditOpportunityProduct_ExtensionV2.fakeMethod();
     OpportunityAndProducts_Controller.fakeMethod();
     CreateScheduleEntries.fakeMethod();
     Opportunity_ReEngineering_Constants.fakeMethod();
  }
  
}